services:
  icecast:
    build: ./icecast
    container_name: icecast
    ports:
      - "8000:8000"
    networks:
      - backend
    restart: unless-stopped
    user: icecast2
    command: ./entrypoint.sh

  liquidsoap:
    build: ./liquidsoap
    container_name: liquidsoap
    ports:
      - "8005:8005"
    depends_on:
      - icecast
    networks:
      - backend
    restart: unless-stopped
    command: liquidsoap /app/script.liq

  postgres:
    image: postgres:15
    container_name: postgres
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
