services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env.test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    restart: unless-stopped
