services:
  icecast:
    build: ./icecast
    container_name: icecast
    networks:
      - backend
    restart: unless-stopped
    user: icecast2
    command: ./entrypoint.sh

  liquidsoap:
    build: ./liquidsoap
    container_name: liquidsoap
    ports:
      - "8005:8005"
    depends_on:
      - icecast
    networks:
      - backend
    restart: unless-stopped
    user: 100:101
    command: liquidsoap /app/script.liq

  postgres:
    image: postgres:15
    container_name: postgres
    networks:
      - backend
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - backend
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
