services:
  icecast:
    env_file:
      - .env.prod
    volumes:
      - ./icecast/icecast_template.xml:/etc/icecast2/icecast_template.xml:ro
      - prod-icecast-logs:/var/log/icecast2

  liquidsoap:
    env_file:
      - .env.prod
    volumes:
      - prod-liq-files:/app/files
      - ./liquidsoap/auth.liq:/app/auth.liq:ro
      - ./liquidsoap/callbacks.liq:/app/callbacks.liq:ro
      - ./liquidsoap/commands.liq:/app/commands.liq:ro
      - ./liquidsoap/globals.liq:/app/globals.liq:ro
      - ./liquidsoap/script.liq:/app/script.liq:ro
      - ./liquidsoap/stream.liq:/app/stream.liq:ro
      - ./liquidsoap/utils.liq:/app/utils.liq:ro

  webapp:
    build: ./webapp
    container_name: webapp
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    environment:
      NODE_ENV: "production"
    networks:
      - backend
    depends_on:
      - postgres
    restart: unless-stopped
    command: ./start.sh

  postgres:
    env_file:
      - .env.prod
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prometheus:
    volumes:
      - ./prometheus.prod.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    env_file:
      - .env.prod

volumes:
  postgres-data:
  prod-icecast-logs:
  prod-liq-files:
