services:
  icecast:
    env_file:
      - .env.dev
    volumes:
      - ./icecast/icecast_template.xml:/etc/icecast2/icecast_template.xml:ro
      - ./icecast/logs:/logs
    ports:
      - "8000:8000"

  liquidsoap:
    env_file:
      - .env.dev
    volumes:
      - ./liquidsoap:/app

  postgres:
    env_file:
      - .env.dev
    ports:
      - "15432:5432"
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.dev
    volumes:
      - minio-data-dev:/data
    networks:
      - backend
    command: server /data --console-address ":9001"

  prometheus:
    volumes:
      - ./prometheus.dev.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    env_file:
      - .env.dev
    volumes:
      - grafana-storage-dev:/var/lib/grafana

volumes:
  grafana-storage-dev:
  dev-postgres-data:
  minio-data-dev:
